# Generated by Django 5.0.3 on 2024-03-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=100)),
                ('numVisits', models.PositiveIntegerField(default=0)),
                ('numLikes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(max_length=100)),
                ('pageURL', models.URLField()),
                ('numViews', models.PositiveIntegerField(default=0)),
                ('catName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q1App.category')),
            ],
        ),
    ]
