# Generated by Django 5.0.4 on 2024-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
