# Generated by Django 5.0.3 on 2024-03-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('salary', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('personName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q1App.works')),
            ],
        ),
    ]
